#!/bin/bash

TRUNKDIR="/work/hyvestrunk"
LOGPATH="$TRUNKDIR"
LIMIT="1000"

AUTHOR=$1

if [ -n "$2" ]; then
    LOGPATH=$(readlink -e $2)
fi

if [ -n "$3" ]; then
    LIMIT=$3
fi


if [ ! -e $LOGPATH ]; then 
    echo "SPECIFIED PATH IS INVALID: [$LOGPATH]"
    exit
fi

COMMITINFO=$(svn log $LOGPATH -l$LIMIT -v | sed -n "/$AUTHOR/,/-----$/ p")

echo "$COMMITINFO"
