#!/usr/bin/env bash

# Copyright (c) 2015 Antonio Murdaca <me@runcom.ninja>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

_docker_running_containers() {
  local current words
  current="${COMP_WORDS[COMP_CWORD]}"
  words="$(docker ps | perl -ne '@cols = split /\s{2,}/, $_; printf "%20s\n", $cols[6]' | tail -n +3 | awk '$1' | xargs)"
  COMPREPLY=($(compgen -W "$words" -- "$current"))

  return 0
}

_docker_shell() {
  local previous=${COMP_WORDS[COMP_CWORD-1]}

  case "${previous}" in
    docker-shell) _docker_running_containers ;;
  esac

  return 0;
}

complete -F _docker_shell docker-shell
